//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoSSISEntities : DbContext
    {
        public DemoSSISEntities()
            : base("name=DemoSSISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Vote_Sept22> Vote_Sept22 { get; set; }
    }
}
