//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int id { get; set; }
        public Nullable<bool> A26 { get; set; }
        public Nullable<bool> A13 { get; set; }
        public Nullable<bool> A28 { get; set; }
        public Nullable<bool> C27 { get; set; }
        public Nullable<bool> A24 { get; set; }
        public Nullable<bool> B19 { get; set; }
        public Nullable<bool> B59 { get; set; }
        public Nullable<bool> B46 { get; set; }
        public Nullable<bool> B52 { get; set; }
        public string Token { get; set; }
    }
}
