//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote_Sept22
    {
        public int id { get; set; }
        public Nullable<bool> DHEERAJ_MISHRA_B21 { get; set; }
        public Nullable<bool> MOHSIN_KHAN_A3 { get; set; }
        public Nullable<bool> ASHISH_GUPTA_A27 { get; set; }
        public Nullable<bool> RAM_KUMAR_B26 { get; set; }
        public Nullable<bool> TARUN_KUMAR_C31 { get; set; }
        public Nullable<bool> ASHISH_TRIPATHI_C29 { get; set; }
        public Nullable<bool> AGRAZ_SHARMA_A17 { get; set; }
        public Nullable<bool> PARWESH_RANJAN_DEEPAK_B13_14 { get; set; }
        public string Token { get; set; }
    }
}
